## Welcome to Jekyll!
##
## This config file is meant for settings that affect your whole blog, values
## which you are expected to set up once and rarely edit after that. If you find
## yourself editing this file very often, consider using Jekyll's data files
## feature for the data you need to update frequently.
##
## For technical reasons, this file is *NOT* reloaded automatically when you use
## 'bundle exec jekyll serve'. If you change this file, please restart the server process.
##
## If you need help with YAML syntax, here are some quick references for you: 
## https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
## https://learnxinyminutes.com/docs/yaml/

# config
show_email: false
show_excerpts: true
show_tags: true
show_header: true
show_footer: true
show_categories: true
show_links_on_homepage: true
show_links_in_header: false
show_posts: true

theme: jekyll-theme-iamlynnmckay

# minima
email: iamlynnmckay@gmail.com
baseurl: "" 
twitter_username: iamlynnmckay
github_username:  iamlynnmckay

# jekyll-seo-tag 
author: "Lynn McKay"
url: "https://iamlynnmckay.com"
title: "@iamlynnmckay"
description: "Lynn's blog about things and stuff."
twitter:
  username: "iamlynnmckay"
  card: "site.twitter.card"
logo: "assets/images/logo.svg"

# jekyll-scholar
scholar:
  style: apa

# plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-scholar
  # - jekyll-postcss

include: 
  - '_pages'
  - 'assets/pages'

# exclude
exclude:
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - _test/
  - assets/posts
  - gemfiles/
  - netlify.toml
  - node_modules/
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
  # - postcss.config.js
  # - purgecss.config.js
